name: wellwerks
description: WellWerks oilfield toolbox and reporting app.
publish_to: 'none'
version: 1.0.1+235

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  signature: ^5.5.0
  path_provider: ^2.1.4
  pdf: ^3.11.1
  printing: ^5.13.2
  share_plus: ^10.1.0
  image_gallery_saver: ^2.0.3
  package_info_plus: ^8.0.2
  vibration: ^3.1.4
  geolocator: ^13.0.2
  http: ^1.2.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  fl_chart: ^0.69.0
  file_selector: ^1.0.3
  qr: ^3.0.2
  qr_flutter: ^4.1.0
  image: ^4.3.0
  mobile_scanner: ^5.2.3
  image_picker: ^1.1.2
  xml: ^6.5.0
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/Wellwerks Complete JSA.pdf
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon_build145.png"
  remove_alpha_ios: true
